spring.application.name=shiptrack

# Database
spring.datasource.url=jdbc:postgresql://localhost:5433/shiptrack_db
spring.datasource.username=shiptrack_user
spring.datasource.password=shiptrack_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Mailtrap
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=6710bba114c3c9
spring.mail.password=2239cea793e146
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT
app.jwt.secret=LclJEvPpJdpBJ50P0uYO18XCTchTEc1d2S9Q188sRAG
app.jwt.expiration=86400000



# Actuator
management.endpoints.web.exposure.include=health